title: Frontend Blog Navigator
description: 前端技术博客与社交媒体导航
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# 添加仓库信息
repository: knight174/frontend-blog-navigator

show_downloads: true

# GitHub Metadata settings
github:
  is_project_page: true
  repository_url: https://github.com/knight174/frontend-blog-navigator
  owner_url: https://github.com/knight174
  owner_name: knight174
